### ISSUE TITLE
Bookmarks Net Radio

### ISSUE THREAD

**Issue by ztormstiql** [krauskopf/node-red-contrib-avr-yamaha#10]
Hello, thanks for all your work! Great nodes!

I have a HTR 4068 and I would like to use the nodes to select a bookmark from Net Radio and start playing. I can't figure out how to do it. Is it possible with the nodes?

Thanks in advance

**Comment by tomrey1** [comment]
I did it like this:
![screen shot 10-08-18 at 10 12 pm](https://user-images.githubusercontent.com/32529355/46631611-31e56080-cb48-11e8-9ca5-9b3f0b121da8.JPG)
![screen shot 10-08-18 at 10 12 pm 001](https://user-images.githubusercontent.com/32529355/46631700-72dd7500-cb48-11e8-98d9-d880339e2c25.JPG)

regards

**Comment by ztormstiql** [comment]
Thanks for your response!
I tried to use the Put Node with the NET_RADIO.List_Control.Direct_Select with the payload Line_1, but nothing happens when I inject something. The AVR In Node returns the following:

{"topic":"NET RADIO.List_Info","payload":{"Menu_Status":"Ready","Menu_Layer":"3","Menu_Name":"My__Favorites","Current_List":{"Line_1":{"Txt":"Radio Veronica","Attribute":"Item"},"Line_2":{"Txt":"Sky Radio 101 FM","Attribute":"Item"},"Line_3":{"Txt":"Qmusic","Attribute":"Item"},"Line_4":{"Txt":"Radio 10","Attribute":"Item"},"Line_5":{"Txt":"NPO Radio 2","Attribute":"Item"},"Line_6":{"Txt":"Freez FM 98.7","Attribute":"Item"},"Line_7":{"Txt":"","Attribute":"Unselectable"},"Line_8":{"Txt":"","Attribute":"Unselectable"}},"Cursor_Position":{"Current_Line":"1","Max_Line":"6"}},"devDesc":{"modelName":"HTR-4068","modelNumber":"4068","serialNumber":"XXXXXXX","modelDescription":"AV Receiver","manufacturer":"Yamaha Corporation","friendlyName":"Woonkamer","presentationURL":"my_url/","udn":"uuid:XXXXXX"},"_msgid":"7595fb89.12c2f4"}

Am I missing something?

This is my flow:
[{"id":"8505e184.247c08","type":"AVR-Yamaha-put","z":"a82f64c3.577b7","device":"1acd74fd.d0f5bb","name":"","topic":"NET_RADIO.List_Control.Direct_Sel","payload":"Line_1","x":460,"y":1140,"wires":[["d027b987.bdbbb8"]]},{"id":"3cf882d5.3a3086","type":"inject","z":"a82f64c3.577b7","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":260,"y":1140,"wires":[["8505e184.247c08"]]},{"id":"d027b987.bdbbb8","type":"debug","z":"a82f64c3.577b7","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":740,"y":1140,"wires":[]},{"id":"1acd74fd.d0f5bb","type":"avr-yamaha","z":"","name":"","address":"myurl","port":"49154","debug":false}]

**Comment by ztormstiql** [comment]
Thanks for your response! Have tried your solution and it works!
