### ISSUE TITLE
Yamaha RX-V679 Error Message on PUT Node

### ISSUE THREAD

**Issue by GasTurbineMan** [krauskopf/node-red-contrib-avr-yamaha#12]
Thank you for your node-red-contrib-avr-yamaha.  I have installed and currently configured to my Yamaha RX-V679 MusicCast receiver.  Everything works well however, every time a command is sent via the PUT node, the command is received at the AVR and AVR functions correctly - but Node-Red always gives me the following message in debug message:
"Received unexpected response data: {"YAMAHA_AV":{"$":{"rsp":"PUT","RC":"0"},"Main_Zone":{"Surround":{"Program_Sel":{"Current":""}}}}}"

Is this something I have configured incorrectly or is this message because my Receiver Model is not entirely compatible with your code?   Other than the message in Node-Red, not sure it is really causing me any adverse issues.  Thanks again for your hard work.

**Comment by krauskopf** [comment]
Thanks for reporting this bug.
Please try the new version 0.8.5 which should fix your issue.

**Comment by GasTurbineMan** [comment]
I am not seeing where version 0.8.5 is and available upgrade from the Node-Red "Manage palette" page.
I tried to simply reinstall using "sudo npm i node-red-contrib-avr-yamaha" command as well, but got errors.
Any special instructions on how to install this upgrade?  Thank you.

**Comment by krauskopf** [comment]
Looks like it toke the node-red flow registry one day to refresh the index. Can you please have a look if the nodes are now available in the palette?

**Comment by GasTurbineMan** [comment]
You are correct.  Update is now available and I completed same update on my machine.  Your contrib is now working without error on my machine.  Thank you.

**Comment by krauskopf** [comment]
Happy to hear. Thank  you for taking the time to report the error and to test the fix. :-)
