### ISSUE TITLE
Errors missing in debug-node when device is off

### ISSUE THREAD

**Issue by tomrey1** [krauskopf/node-red-contrib-avr-yamaha#14]
Great nodes! (I'm using them already for several years in a wake-up-scenario within my home-automation)
Today I ran into the following issue:
Trying to test my device-condition, I realized, that all Yamaha-nodes are throwing error messages only to their output, if the device is on.
If the device is off (no power supply) or during start, the nodes are producing error-strings but not throwing them to their output.
Therefore I am not able to use this info in my flow (e.g. wait until device ist fully present).
My workaround is just waiting 15 sec. but...

**Comment by krauskopf** [comment]
Hi @tomrey1,
thanks for your report. I've pushed a fix with version 0.8.6, which triggers the catch node if the message could not be send. See https://cookbook.nodered.org/basic/trigger-on-error for an example. Please let me know if this fixes your issue.
Best Regards
Sebastian

**Comment by tomrey1** [comment]
Hallo Sebastian, besser auf Deutsch:

Danke für die schnelle Reaktion.

Ich hätte allerdings erhofft, daß du einen Fehlercode einbauen würdest i.S., von msg.error: FC 0 bzw. 9 an einem 2. Output. 

Damit wäre if-then leichter (ich mache: if FC#0, dann Steckdose ein und pings auf den Yamaha“) und msg.string bliebe für den „Produktiv-flow“ frei.

Aber besser so als gar nicht.

Grüße

Thomas

 

Von: krauskopf [mailto:notifications@github.com] 
Gesendet: Dienstag, 6. August 2019 13:11
An: krauskopf/node-red-contrib-avr-yamaha
Cc: tomrey1; Mention
Betreff: Re: [krauskopf/node-red-contrib-avr-yamaha] Errors missing in debug-node when device is off (#14)

 

Hi @tomrey1 <https://github.com/tomrey1> ,
thanks for your report. I've pushed a fix with version 0.8.6, which triggers the catch node if the message could not be send. See https://cookbook.nodered.org/basic/trigger-on-error for an example. Please let me know if this fixes your issue.
Best Regards
Sebastian

**Comment by krauskopf** [comment]
Hallo Thomas,

danke für Dein Feedback. Ich hatte ursprünglich auch überlegt, ob ich im Fehlerfall den flow weiterlaufen lasse und einen statusCode in der msg zurückgebe. Hab mich dann aber für den catch-node entschieden, da so das Verhalten der Nodes kompatibel bleibt und der catch-node von Node-Red als "Standardlösung" für Fehler-handling vorgesehen ist.

Wenn du aber im anderen Ansatz wesentliche Vorteile siehst, dann könnte ich die Variante als Option ("Continue flow on error") versuchen mit einzubauen.

Grüße
Sebastian

**Comment by tomrey1** [comment]
Hallo Sebastian, ja mit Statuscode wäre das m.E. wesentlich besser. Ein Beispiel:

In einer Weckfunktion bekommt der Tux-Server einen Aufweckbefehl meiner SPS (Hausteuerung) mit z.B. 4 Minuten Vorlaufzeit (WOL + http-get).

Daraufhin läuft in Node-Red ein Timer, der den Vorlauf runterzählt um pünktlich die Zone im Schlafzimmer zu unmuten.

Parallel testet (ping) und startet der Flow eine Netzwerksteckdose, an der der Yamaha hängt.

Danach wird dieser gestartet und nach seinem eigenen Startvorlauf wird über Input Server ein Radiostream aus der fritzbox aufgerufen.

Abhängig vom Fehlercode, könnten bestimmte Flow-Bereiche wiederholt werden, ohne daß die Weck-Vorlaufzeit verändert würde.

Ich hoffe, ich habe das verständlich rübergebracht.

Schöne Grüße

Thomas 

Von: krauskopf [mailto:notifications@github.com] 
Gesendet: Freitag, 9. August 2019 15:23
An: krauskopf/node-red-contrib-avr-yamaha
Cc: tomrey1; Mention
Betreff: Re: [krauskopf/node-red-contrib-avr-yamaha] Errors missing in debug-node when device is off (#14)

 

Hallo Thomas,

danke für Dein Feedback. Ich hatte ursprünglich auch überlegt, ob ich im Fehlerfall den flow weiterlaufen lasse und einen statusCode in der msg zurückgebe. Hab mich dann aber für den catch-node entschieden, da so das Verhalten der Nodes kompatibel bleibt und der catch-node von Node-Red als "Standardlösung" für Fehler-handling vorgesehen ist.

Wenn du aber im anderen Ansatz wesentliche Vorteile siehst, dann könnte ich die Variante als Option ("Continue flow on error") versuchen mit einzubauen.

Grüße
Sebastian

**Comment by krauskopf** [comment]
Mir fehlt leider die Zeit um die Alternative mit den Status-Codes inzubauen. Da aber mit dem Catch-Node eine Lösung existiert welche dem Node-RED Standard entspricht würde ich dieses Issue hier schließen.
