### ISSUE TITLE
RX-V775 Output 2

### ISSUE THREAD

**Issue by pawel9012** [krauskopf/node-red-contrib-avr-yamaha#15]
Hi,

First of all, I would like to say that the node works with RX-V775. Only the HDMI OUT 2 option is missing. Is it possible to add this?

**Comment by krauskopf** [comment]
Hi,
happy to hear, that it works with you RX-V775. Can you be a little bit more specfic which optin to add for HDMI OUT 2? Maybe by naming an option for HDMI OUT 1, that you are missing for 2?

**Comment by krauskopf** [comment]
Thanks for the info. I have added some HDMI OUT 2 topics with version v0.8.7. Hope this helps. Otherwise please reopen.
