### ISSUE TITLE
RX-V3900 iPod Control

### ISSUE THREAD

**Issue by BeryBurnout** [krauskopf/node-red-contrib-avr-yamaha#17]
doesn´t work with the commands i can select so i played a little bit and found some solution:
Input select is simply **iPod** (using the supplied iPod Dock)
Topic: **iPod.Play_Control.Play** commands **Play Pause Stop**
Topic: **iPod.Play_Control.Skip** commands **Fwd Rev**
can you please implement these ?

**Comment by BeryBurnout** [comment]
Volume settings:
Topic for fixed values: **Main_Zone.Vol.Lvl.Val**
Payload unchanged like in the examples  {"Val":"-400","Exp":"1","Unit":"dB"}
Topic for Volume + - : **Main_Zone.Vol.Up_Down** 
Payload only **Up** or **Down** 
have not found yet a possibility to change by 5 dB

**Comment by krauskopf** [comment]
Thanks for the info. I have added some iPod topics with version v0.8.7. Hope this helps. Otherwise please reopen.
