### ISSUE TITLE
Cannot load scene

### ISSUE THREAD

**Issue by afrixx** [krauskopf/node-red-contrib-avr-yamaha#18]
Hello together,
thanks for that great Node-RED library! It works fine, to power on, select input, volume and more...

But I don't get the scene loading to work.
I have 4 scene buttons at my RX-V500D. One is called "TV": When clicking this button, my TV automatically switches on.
Now I want to use this scene also from Node-RED to switch on my TV.

But when using the command "Main_Zone.Scene.Scene_Load" with payload "Scene 2", I always get this response:
`"Received error response code: "2""`
When I change Scene 2 to something other, then I get error code 3.

Is there a bug? Is there a mistake on my side?

Thanks for your help!

**Comment by krauskopf** [comment]
Just tried it myself here on my V677 and I can successfully switch the scenes. Here's my flow as example code:

![grafik](https://user-images.githubusercontent.com/1938031/104359085-8dfd7300-550f-11eb-8a5f-cf273a0379f9.png)

`[{"id":"3000ecee.bd04b4","type":"AVR-Yamaha-put","z":"56e20b5d.c407ec","device":"7c77582b.2f501","name":"Switch Scene 1","topic":"Main_Zone.Scene.Scene_Load","payload":"Scene 1","x":340,"y":120,"wires":[["55e920f9.2c8e5"]]},{"id":"375bcf5b.6b92f","type":"inject","z":"56e20b5d.c407ec","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":120,"wires":[["3000ecee.bd04b4"]]},{"id":"55e920f9.2c8e5","type":"debug","z":"56e20b5d.c407ec","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":610,"y":120,"wires":[]},{"id":"4b7bb8f5.e9f0d8","type":"AVR-Yamaha-put","z":"56e20b5d.c407ec","device":"7c77582b.2f501","name":"Switch Scene 2","topic":"Main_Zone.Scene.Scene_Load","payload":"Scene 2","x":340,"y":180,"wires":[["55e920f9.2c8e5"]]},{"id":"72935c5e.3990f4","type":"inject","z":"56e20b5d.c407ec","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":180,"wires":[["4b7bb8f5.e9f0d8"]]},{"id":"7c77582b.2f501","type":"avr-yamaha","z":"","name":"","address":"192.168.17.151","port":"","debug":false}]`

**Comment by afrixx** [comment]
Thank you, @krauskopf for your snippet.
I get the same error as before... :|

![grafik](https://user-images.githubusercontent.com/50923486/104495803-7c33d280-55d8-11eb-9b94-5480c440a56c.png)

Perhaps there are differences in the API depending on the Yamaha AVR model...
Do you know what response code 2 means?

**Comment by krauskopf** [comment]
I never found an official list of response codes for the old YNCA protocol. But in the new YEC protocol (MusicCast) the response codes are:
2 - internal error
3 - invalid request
Don't know if the are the same, but might be likely. 

Unfortunately I do not have a spec for the RX-V500. But I have another idea, that you can try. Does your AVR also have a web interface, that you can access via browser? If so, then please open with browser, enter developer mode by pressing F12 and then open the network analyzer. After that press the button for "scene 2" and look in the log file for the API command, that is send.

Here how this look for me:
![grafik](https://user-images.githubusercontent.com/1938031/104500256-79d47700-55de-11eb-871b-0ba6648d46e5.png)

Maybe this way we can find the command for your AVR. The response in the response tab ("Antwort") would also be interesting to know.

**Comment by afrixx** [comment]
My AVR is too old to have a UI web interface to control it.
I am only able to update the firmware and do some network configuration in browser.
![grafik](https://user-images.githubusercontent.com/50923486/104505544-57455c80-55e4-11eb-994f-aea2b1c4a6ce.png)

The Android App works too, but there I cannot use the developer console :| .

But thank you very much for your help! I think the problem is based on the API of my receiver.

**Comment by afrixx** [comment]
Did another try with Postman - same result:

![grafik](https://user-images.githubusercontent.com/50923486/104508818-126ff480-55e9-11eb-81f5-2415b96ab757.png)

I will close that issue because of the device specific problem.

**Comment by krauskopf** [comment]
I found another API endpoint: `Main_Zone.Scene.Scene_Sel`

Seems to also change scenes on my AVR. Maybe worth a try.

`[{"id":"55e920f9.2c8e5","type":"debug","z":"56e20b5d.c407ec","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":710,"y":280,"wires":[]},{"id":"4b7bb8f5.e9f0d8","type":"AVR-Yamaha-put","z":"56e20b5d.c407ec","device":"7c77582b.2f501","name":"Switch Scene 2","topic":"","payload":"","x":500,"y":280,"wires":[["55e920f9.2c8e5"]]},{"id":"72935c5e.3990f4","type":"inject","z":"56e20b5d.c407ec","name":"","topic":"Main_Zone.Scene.Scene_Sel","payload":"Scene 2","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":210,"y":280,"wires":[["4b7bb8f5.e9f0d8"]]},{"id":"7c77582b.2f501","type":"avr-yamaha","name":"","address":"192.168.17.151","port":"","debug":false}]`


Also: Did you upgrade to the latest firmware version? https://de.yamaha.com/de/products/audio_visual/av_receivers_amps/rx-v500d/downloads.html

**Comment by afrixx** [comment]
YEAAAH! Du bist genial!!!

Thank you very much, @krauskopf ! This endpoint works perfectly!
Even when the receiver is in stand-by, it wakes up and starts my TV, exactly what I wanted to realize!
You made my day! :)

Should I create a pull request to add the command to the DropDown?

Firmware is already the latest.

**Comment by krauskopf** [comment]
Freut mich zu hören ;-)

Pull-Request would be highly appreciated! Thx...
