### ISSUE TITLE
Not receiving events

### ISSUE THREAD

**Issue by travisghansen** [krauskopf/node-red-contrib-avr-yamaha#2]
What are the events that should be emitted by the `AVR-Yamaha-in` node?  I'm switching inputs, volume, etc, etc and not seeing anything triggered.

Thanks!

**Comment by krauskopf** [comment]
Please have a look at version 0.7.0 where I made some additional changes. Now you should see events on (Power, Volume, Input selection change, play info change like selected track and list info change when menu changes). 

Also make sure to write 'System.Misc.Event.Notice' to 'On' by using the 'Put' node.

**Comment by travisghansen** [comment]
OK, I've updated to `0.7.0` and sent the `System.Misc.Event.Notice` to `On` via the `Put` node.  Still nothing coming through in terms of events.  I tried that with the 3 different models I have and none of them work.

I'm not sure how this is supposed to work.  If the messages are broadcast on the network do you have any tips on how I can sniff/monitor the traffic to make sure it's even making it to my box (maybe firewall rules are causing an issue)?

Additionally, I'm not sure if the specific models I own may not have the feature although I'd be surprised by that given that the android app seems to update quickly when out of band changes are made.

**Comment by travisghansen** [comment]
OK, I've done some research with `tcpdump -n udp dst port 1900` and it's an issue with my network not the node.

Events work with:
- TSR-5790
- RX-A740

Do **not** work with:
- HTR-4065

It's probably out of your control but I was surprised to see the MUTE/UNMUTE notices simply send the current volume level (with out indication of muted or unmuted).  Would be nice to see that sane.

Regarding my network, I'm in a bit of an abnormal setup.  I'm running Node-RED inside docker inside a VM in openstack.  Long story short it appears broadcast traffic isn't making it's way down into the VM so I'll be digging into that.

Thanks!

**Comment by krauskopf** [comment]
Regarding the mute/unmute thing: It is indeed impossible to detect if the 'Volume' event was send because of volume level change or muting/unmuting. 
But I changed the code, so that the node now emits both states when the event was detected. Have a look at 0.7.1.

**Comment by travisghansen** [comment]
Ah I see.  I don't think that's how I'd approach it but frankly there unfortunately likely isn't a 'clean' way to do it with the tools yamaha provides solely.  I think no matter how it's approached it requires some sort of stateful cache that has to do a lookup to determine the last known state and compare it with the new.

I personally would probably leave it as it was and as a developer/consumer of the API I'd just need handle the lookup manually (get the mute value, and/or any cached values) rather than generating 2 events/msgs in node.  Just my 2 cents.

Any any case thanks for great nodes and being so responsive and helpful!

**Comment by krauskopf** [comment]
thx for the feedback. I had the same concerns as you, but came to the conclusion, that emitting both states is the lesser evil. I don't want to introduce any statefull behaviour to the nodes, as it would make things more complex and I can not prevent any messed up state. I mean, it starts with the events being UDP multicast which don't have any guarantee.

Also you can filter out the mute state using the RBE node (http://flows.nodered.org/node/node-red-node-rbe) Unfortunately this node does not work if the payload is a JSON object. Makes me think if I should stringify the payload? On the other hand, the user can also stringify the output.

In any case. I like to have the nodes more simple (even if it requires the user to handle the corner cases explicit) instead of building implicit mechanisms which might not work 100% of the time.

**Comment by travisghansen** [comment]
I like your thought process.  I certainly would not recommend the nodes themselves try to store a state, let the end-user store it in a function context (or global I suppose) or redis/etc.  My thought process was: without the double event (the previous behavior) I would only need to store/cache **1** value (previously known mute state) to determine what _really_ happened.  As is I'd need to store **2** values to know what _really_ happened.  Of course as you mentioned it would be pretty easy via RBE or a function node to filter out the mute/unmute messages so not a big deal either way.

Thanks!
