### ISSUE TITLE
V500D

### ISSUE THREAD

**Issue by gj52** [krauskopf/node-red-contrib-avr-yamaha#20]
Hallo, my test flows

`[{"id":"b9eec055.4b70b","type":"AVR-Yamaha-put","z":"243c666c.5048ba","device":"86ededb4.cf661","name":"DAB","topic":"Main_Zone.Input.Input_Sel","payload":"DAB","x":1330,"y":880,"wires":[["197dba14.fdd726"]]},{"id":"c06ff3a.943cc1","type":"inject","z":"243c666c.5048ba","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"DAB","payloadType":"str","x":1170,"y":880,"wires":[["b9eec055.4b70b"]]},{"id":"197dba14.fdd726","type":"debug","z":"243c666c.5048ba","name":"DAB","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":1490,"y":880,"wires":[]},{"id":"86ededb4.cf661","type":"avr-yamaha","name":"V500D","address":"192.168.0.52","port":"8080","debug":true}]`

Debug reply

```
1/18/2021, 12:05:19 PMnode: V500D
msg : string[33]
"Received error response code: "3""
1/18/2021, 12:05:19 PMnode: DAB
msg.payload : string[3]
"DAB"
```

second flow

`[{"id":"17955f0e.45cbb1","type":"AVR-Yamaha-put","z":"243c666c.5048ba","device":"86ededb4.cf661","name":"#1","topic":"Tuner.Play_Control.Preset.Preset_Sel","payload":"1","x":1330,"y":940,"wires":[["7c6a16d2.a64868"]]},{"id":"7c6a16d2.a64868","type":"debug","z":"243c666c.5048ba","name":"Sel#1","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":1470,"y":940,"wires":[]},{"id":"374127c1.1cd488","type":"inject","z":"243c666c.5048ba","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"1","payloadType":"num","x":1170,"y":940,"wires":[["17955f0e.45cbb1"]]},{"id":"86ededb4.cf661","type":"avr-yamaha","name":"V500D","address":"192.168.0.52","port":"8080","debug":true}]`

reply

```
1/18/2021, 12:06:47 PMnode: V500D
msg : string[33]
"Received error response code: "2""
1/18/2021, 12:06:47 PMnode: Sel#1
msg.payload : number
0x1
```

any idea?

Thanks
send me a PM for help ;-)

**Comment by afrixx** [comment]
Hello @gj52 ,
"DAB" is not allowed as "Input_Sel" parameter. I have the same receiver and tested your flows.
You have to select "Tuner" as input.
This command jumps to the last heard radio program.

The command "Tuner.Play_Control.Preset.Input_Sel" seems not to be supported by the V500D.
