### ISSUE TITLE
Cannot set System.Misc.Event.Notice to On - "Received error response code: "4""

### ISSUE THREAD

**Issue by manoloxxl** [krauskopf/node-red-contrib-avr-yamaha#23]
Hi,

I'm not able to set System.Misc.Event.Notice to on. It is allways off. When i set the PUT i only receive the message "Received error response code: "4"".

Any idea how i can fix this issue?

Best Regards

**Comment by krauskopf** [comment]
Code 4 means "Invalid Parameter (Out of range, invalid charactersetc.)". Currently don't have a hardware to test, but maybe try upper case "On"?

**Comment by manoloxxl** [comment]
I've found the issue - mistake by me. The receiver was not "powered on", it was in "standby". 

The command only is accpected when the receiver is "on".
