### ISSUE TITLE
Can't connect to receiver

### ISSUE THREAD

**Issue by ChopOMatic** [krauskopf/node-red-contrib-avr-yamaha#3]
Can't get it to connect to my RX-A3060BL, which is easily accessible via the built-in web control pages. (`http://IPADDRESS` alone returns a simple web control panel, while `http://IPADDRESS/setup` returns a very detailed config page for the receiver.)

![2017-01-02_18-38-57](https://cloud.githubusercontent.com/assets/8518789/21598073/3e0e20dc-d11b-11e6-8ecd-dc3a51895e46.png)

**Comment by krauskopf** [comment]
hi,

to track down the error I need some more information. Please try the following:

- Activate the "debug log" setting in the corresponding configuration node and then look in the stdout of node-red for some debug outputs. Paste them here.
![image](https://cloud.githubusercontent.com/assets/1938031/21786598/f6783aa0-d6c4-11e6-99a8-b5a37fbb781b.png)

On a raspberry pi with raspbian you can show the log on the terminal with the following command:
`sudo journalctl -f -u nodered -o cat`

- Change the flow above to trigger the "yamaha GET Node" manually using an inject node:
![image](https://cloud.githubusercontent.com/assets/1938031/21786793/1997db5c-d6c6-11e6-98e6-669212cf4860.png)
![image](https://cloud.githubusercontent.com/assets/1938031/21786803/25a537aa-d6c6-11e6-8b16-645d42d500dc.png)

Is this working?

- In the configuration of the receiver, is there anywhere an option which is called "remote control port" or similar? Maybe the RX-A3060BL is not listening on port 8080? Other models, like the TSR-5790 use for example port 49154.

Let me know if you have further questions or need more detailed instructions.

Regards,
Sebastian
