### ISSUE TITLE
error on yamaha node

### ISSUE THREAD

**Issue by jormus** [krauskopf/node-red-contrib-avr-yamaha#4]
hi

when I connect "AVR Yamaha", directly to debug, I get
msg : string[95]
"Failed to decode UPnP Device Description. Error: TypeError: Cannot read property 'root' of null"

I tried everything, but can not get status update :(

Can somebody help me?

**Comment by krauskopf** [comment]
Hi, 

could you please give some more details? What AVR model are you using? Which operating system? Version oder nodejs? ...

Are the Get and Put node? Are these working?

**Comment by jormus** [comment]
hi,

running on debian jessie (8)
node.js = V7.10.0
npm = 4.2.0
node-red = 0.16.2

AVR = RX-V475 firmware = 1.3
The get and put node are working, meaning:
I control the power = ok
I control the volume, with the db value (get db first then slider range between min and max decibel) because up/down on input didn't work. 

I can wireshark the broadcast message if you want, but I can confirm the receiver broadcasts' when I change the value, on port 80

Thx for looking in too this, if you want more info, im happy to help

![image](https://user-images.githubusercontent.com/1336329/27608261-123594e4-5b87-11e7-85ed-199d2aa3bb4f.png)

**Comment by krauskopf** [comment]
Hi Jormus,

sorry for the delay. I've been a little bit busy the last two weeks. Thanks for the information, but I have an additional question. 
The error message is raised, when the node fails to parse the xml renderer description of the AVR. This file can also be accessed through the browser. Simply append `:8080/MediaRenderer/desc.xml` after the IP address of your AVR. Port can be different. At least for my RX-V677 the default port ist 8080.

Example:
![image](https://user-images.githubusercontent.com/1938031/28240069-644c8e76-697a-11e7-9ad1-5483f83127c2.png)

Can you please try to access this file on your AVR and if successfull post the resulting XML content here?

**Comment by jormus** [comment]
hi,
here is my output. I changed the uuid :-)

I put the whole xml in zip, easy for you to read then.

thx


[yamaha.zip](https://github.com/krauskopf/node-red-contrib-avr-yamaha/files/1150931/yamaha.zip)

**Comment by krauskopf** [comment]
Strange, could not find any errors, other than the wrong encoding of the ampersand. But this is probably because you copy and pasted from the browser instead of file->save as?
I added some more logging in case of error. Could you please rerun and post the error log here? Thanks...

**Comment by jormus** [comment]
ok, i did the save as, like you want :-)

is a bit difference.

[desc.zip](https://github.com/krauskopf/node-red-contrib-avr-yamaha/files/1168173/desc.zip)

I try the update of the node later on

**Comment by krauskopf** [comment]
Thanks, the device description definitely looks okay. Looks good, when I fake the input stream and inject your data.

![image](https://user-images.githubusercontent.com/1938031/28501072-40d2101e-6fd4-11e7-9d6e-d786996c9f63.png)

**Comment by krauskopf** [comment]
Hi jormus, any update on this?
