### ISSUE TITLE
Possible to open/access the original original yamaha-nodejs library?

### ISSUE THREAD

**Issue by tomrey1** [krauskopf/node-red-contrib-avr-yamaha#7]
Hi, after some trial and errors with your nodes and my A3030 I'd like to add the missing  functions for my AVR. If I unterstand correctly th original yamaha-nodejs library by Pascal Seitz cyn be changed through a simple text file. Can i get to this through your node or can I install the Pascal Seitz node in node red directly/additionally? Sorry for proably silly questions but I am pretty new to node-red.
Thanks in advance Thomas

**Comment by krauskopf** [comment]
Hi Thomas,
by text-file you mean this? https://github.com/krauskopf/node-red-contrib-avr-yamaha/blob/master/references.js. This list is not part of Pascal's library, but done by me.

Which properties do you want to access on your A3030? Maybe I can try to add them.
Please describe a little bit more what you are trying to do. 

Regards,
Sebastian

**Comment by tomrey1** [comment]
Hi Sebastian,
thanks for your answer. I was referring to:
[https://github.com/PSeitz/yamaha-nodejs/blob/master/availableCommands.txt](url)
But it seems to me, that your references.js has the same function - correct?
Could I simply change references.js or are there other implications?
In the meanwhile I solved my issue with node-red simply making my own exec-nodes for the required functions (mainly Zones 2+3) and direct curls from my wago-plc. No doubt, your way is by far more elegant. Regards Thomas

**Comment by krauskopf** [comment]
Hi Thomas,
thanks for the response. Seems like Pascal improved the library, since I started to use it.

Extending the reference.js with new nodes should be no problem. I've added some more topics for Zone3+4. Perhaps the ones you need are now available.

Also note, that you can set a topic which is missing in the references, by using the msg object (`msg.topic`) and leaving the selection in the AVR node empty. See Example4 in the updated readme.

Best Regards,
Sebastian

**Comment by tomrey1** [comment]
Hi Sebastian,
thanks a lot, I’ll be able to test early December on site and you’ll have my feedback then.
Regards Thomas
 
Von: krauskopf [mailto:notifications@github.com] 
Gesendet: Sonntag, 5. November 2017 15:33
An: krauskopf/node-red-contrib-avr-yamaha
Cc: tomrey1; State change
Betreff: Re: [krauskopf/node-red-contrib-avr-yamaha] Possible to open/access the original original yamaha-nodejs library? (#7)
 
Hi Thomas,
thanks for the response. Seems like Pascal improved the library, since I started to use it.
Extending the reference.js with new nodes should be no problem. I've added some more topics for Zone3+4. Perhaps the ones you need are now available.
Also note, that you can set a topic which is missing in the references, by using the msg object (msg.topic) and leaving the selection in the AVR node empty. See Example4 in the updated readme.
Best Regards,
Sebastian

**Comment by krauskopf** [comment]
Hi Thomas,

any update on this?

Best Regards,
Sebastian

**Comment by tomrey1** [comment]
Sorry I had answered by mail..
It's working perfectly, thanks a lot!
Regards Thomas
