### ISSUE TITLE
error after firmware update

### ISSUE THREAD

**Issue by rollercontainer** [krauskopf/node-red-contrib-avr-yamaha#9]
Hi, I've got a RX-A1060. It worked till the last firmware update. Now I got these error message:
"Failed to decode UPnP Device Description. Error: TypeError: Cannot read property 'root' of null" and "This is the parser result which might be wrong: null"
My plugin version is 0.8.2, 
Firmware on AVR is 1.32

How can I help to get it back to work?

**Comment by rollercontainer** [comment]
Mute and Volume messages are still working btw:
{"topic":"Main_Zone.Volume.Mute","payload":"Off","_msgid":"51c02492.7d555c"}

**Comment by krauskopf** [comment]
Hi,

I've updated to the latest version of my RX-V677 (v1.98 from Dec 17), but still works.

Can you please try to access the UPnP Device Description with your browser? To do this, you need to enter the following URL:
http://IP-address-of-your-AVR:8080/MediaRenderer/desc.xml (e.g.: http://192.168.1.151:8080/MediaRenderer/desc.xml)

Does your browser show a xml file? Can you please post the content here, or send via mail to mail@sebakrau.de? You may want to erase the serial number in the xml if you want ;-).

Thanks for your help.

**Comment by rollercontainer** [comment]
Hi, Port 8080 is not answering. I made a full scan and following Ports are open: 80, 5000, 49153, 49154, 50000
Searching after your link I found this: https://community.home-assistant.io/t/support-for-new-yamaha-receivers-and-musiccast-devices/17001 
I tried http://x.x.y.z:49154/MediaRenderer/desc.xml and got the xml file.

**Comment by rollercontainer** [comment]
Changed the port in the config tab to 49154. Deploys without errors. 
Changing a scene results in "Failed to request data from AVR with error: 400".

**Comment by rollercontainer** [comment]
Updated to v 0.8.4 and its working again. Thanks a lot for your work!
